
server:
  port: 8083

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: post-service-route
          uri: lb://post-service
          predicates:
            - Path=/posts/**


        - id: comment-service-route
          uri: lb://comment-service
          predicates:
            - Path=/comments/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


